[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  revision = "b26b538f693051ac6518e65672de3144ce3fbedc"

[[constraint]]
  name = "github.com/renstrom/fuzzysearch"
  revision = "2d205ac6ec17a839a94bdbfd16d2fa6c6dada2e0"
