apiVersion: v1
clusters:
- cluster:
    certificate-authority: $HOME/.minikube/ca.crt
    server: https://$MINIKUBE_IP:8443
  name: minikube
- cluster:
    certificate-authority: $HOME/.minikube/ca.crt
    server: https://$MINIKUBE_IP:8443
  name: us-west1
- cluster:
    certificate-authority: $HOME/.minikube/ca.crt
    server: https://$MINIKUBE_IP:8443
  name: us-east1
- cluster:
    certificate-authority: $HOME/.minikube/ca.crt
    server: https://$MINIKUBE_IP:8443
  name: us
contexts:
- context:
    cluster: us-west1
    user: example-us@possibly-gmail.com
  name: "kubensx-assoc:example-us@possibly-gmail.com:us-west1"
- context:
    cluster: us-east1
    user: example-us@possibly-gmail.com
  name: "kubensx-assoc:example-us@possibly-gmail.com:us-east1"
- context:
    cluster: cluster-that-no-longer-exists
    user: example-us@possibly-gmail.com
  name: "kubensx-assoc:example-us@possibly-gmail.com:cluster-that-no-longer-exist"
- context:
    cluster: us-east1
    user: user-that-no-longer-exists
  name: "kubensx-assoc:user-that-no-longer-exists:us-east1"
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: $HOME/.minikube/client.crt
    client-key: $HOME/.minikube/client.key
- name: example@possibly-gmail.com
  user:
    client-certificate: $HOME/.minikube/client.crt
    client-key: $HOME/.minikube/client.key
- name: example-us@possibly-gmail.com
  user:
    client-certificate: $HOME/.minikube/client.crt
    client-key: $HOME/.minikube/client.key
